'use strict';

module.exports = {
    restApiKey: 'X-LIQUIDITY-REST-API-Key',
    maxFileSize: 10000000, // file size in bytes which is equal to 10 MB
    fileType: [ 1, 2, 3, 4 ],
    userId: '5cbe911eedf2d821b867c1f1',
    dataRoom: {
        1: 'ShareholderContact',
        2: 'LockUp',
        3: 'ByLaws',
        4: 'Rule701Disclosure',
    },
    emailPattern: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    shareHolderIssuanceType: [ 'common', 'preferred' ],
    issuanceType: {
        ALL: 1,
        COMMON: 2,
        PREFERRED: 3,
        INDIVIDUAL: 4,
    },
    userType: {
        1: 'board_member',
        2: 'management',
        3: 'preferred',
        4: 'common',
        5: 'advisor',
    },
    passwordPattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%\-*?&#:;'",.^*(){}\\\/|+=_`~\[\]\<\>])[A-Za-z\d@$!%*?&#:;'",.^\-*(){}\\\/|+=_`~\[\]\<\>]{8,}$/,
    positionType: [ 'board_member', 'management', 'advisor', 'common' ],
    addEditIssuanceType: [ 'equity', 'debt', 'investment fund','convertible note', 'other' ],
    location: [ 'us', 'europe', 'canada', 'australia', 'east-asia', 'south-america', 'middle-east', 'south-asia', 'africa', 'world-wide' ],
    locationKeyValue: {
        'us': 'U.S',
        'europe': 'Europe',
        'canada': 'Canada',
        'australia': 'Australia',
        'east-asia': 'East Asia',
        'south-america': 'South America',
        'middle-east': 'Middle East',
        'south-asia': 'South Asia',
        'africa': 'Africa',
        'world-wide': 'Worldwide',
    },
    issuanceTypeKeyValue: {
        'equity': 'Equity',
        'debt': 'Debt',
        'investment fund': 'Investment fund',
        'convertible note': 'Convertible Note',
        'other': 'Other',
    },
    adminSPCRD: '4921504',
    adminSPCompanyName: 'Liquidity Capital',
    // adminSPEmail: 'support@liquidity.digital',
    issuanceSpAdminEmail: 'deals@yopmail.com',
    issuanceSpAdminName: 'Gavin Racz',
    emptyUserDistribute: {
        1: 'No shareholders found',
        2: 'No common shareholders found',
        3: 'No preferred shareholders found',
        4: 'No member found',
    },

    // Analytics constants
    eventCatagory: {
        watchVideo: 'Watch Video',
        participated: 'Participate Confirm',
        favorite: 'Favorite',
        viewIssuance: 'View Details',
        documents: 'Documents',
        viewOrganization: 'View Organization',
        contactSourcingParty: 'Contact sourcing party',
    },
    interestType: {
        viewed: 'Viewed',
        interested: 'Interested',
        participated: 'Participated',
    },
    interestEventArray: [ 'watchVideo', 'viewIssuance', 'documents', 'viewOrganization', 'favorite', 'contactSourcingParty' ],
    interestTypeArray: [ 'viewed', 'interested', 'participated' ],
    interestEventParticipate: 'participated',
    payableIn: [ 'oz', 'usd' ],
    schedule: [ 'bullet', 'sinking' ],
    typeOfUsers: [ 'broker', 'qualified-purchaser' ],
    DDPUserType: {
        admin: 'admin',
        broker: 'broker',
        qualifiedPurchaser: 'qualified-purchaser',
        issuance: 'issuance',
        user: 'user',
    },
    dayInMilliseconds: 1000 * 60 * 60 * 24,
    cookieName: {
        admin: 'liquidity_admin',
        broker: 'liquidity_broker',
        'qualified-purchaser': 'liquidity_qualified_purchaser',
        issuance: 'liquidity_issuance',
    },
    favIssuancesBasedOnUserType: {
        admin: 'favouriteIssuance',
        broker: 'brokerId.favouriteIssuance',
        'qualified-purchaser': 'QPId.favouriteIssuance',
    },
    userReferrenceId: {
        admin: '_id',
        broker: 'brokerId._id',
        'qualified-purchaser': 'QPId._id',
    },
    analyticsDateFormat: 'YYYY-MM-DD',
};
